version: '3.4'
services:
  mock:
    image: local-mockserver:dev
    build:
      dockerfile: mock.dockerfile
    volumes:
      - mockserver:/root/.castlemock:cached
    ports:
      - "9001:8080"
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    container_name: dev-nextjs-restaurant
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
volumes:
  mockserver: