version: '3.4'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    container_name: nextjs-restaurant
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next