version: '3.4'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    container_name: nextjs-restaurant
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production