name: CI CD
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  run_test:
    runs-on: [ self-hosted, prod ]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Build and test
        run: |
          docker compose up -d --build --force-recreate
          docker compose run app npm test
      - name: Stop and remove containers
        run: docker compose down -v
  deploy:
    runs-on: [ self-hosted, prod ]
    needs: run_test
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Deploy
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
        run: |
          docker compose -f docker-compose.pro.yaml up -d --build --force-recreate