on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.12.0]
    steps:
      - uses: actions/checkout@v3
        with:
         clean: false
      - name: Use nodeJS ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Change directory
        run: cd /home/nextjs/actions-runner/_work/restaurantqr-frontend/restaurantqr-frontend
      - run: pm2 reload 0