on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.12.0]
    env:
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}
    steps:
      - uses: actions/checkout@v3
      - name: Use nodeJS ${{matrix.node-version}}
        uses: actions/checkout@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm
      - run: npm ci
      - run: npm run build --if-present